### ISSUE TITLE
Bot Raid Protection

### ISSUE THREAD

**Issue by Pierre-Demessence** [Unity-Developer-Community/UDC-Bot#16]
Need to remake https://github.com/Sirush/UDHBot/pull/112 in this repo

**Comment by SimplyJpk** [comment]
I'll implement it using the same logic as the setup as [Sirush#112](https://github.com/Sirush/UDHBot/pull/112) but I'll make this into a proper service with a command that can be used to enable it manually with some sort of cooldown before it automatically turns back off.

**Comment by SimplyJpk** [comment]
Do we still need this? Does wick do this? If we do still need something, was the original solution to just kick any new joins after X number of people join at the same time acceptable?

Think I got most of the way with this, but stopped. I'll see if this was complete and try testing it sometime in the next couple days.

**Comment by Pierre-Demessence** [comment]
Wick has this feature but only on premium.
So that might still be good to have, especially since you already did some work and it would be a shame to waste it!

**Comment by Pierre-Demessence** [comment]
Same reason than #29:
> Closing this as for now we have Wick, and unless we see that Wick is not sufficient there's no need to merge this.
