### ISSUE TITLE
Profile Card & Top/TopKarma sometimes doesn't appear

### ISSUE THREAD

**Issue by SimplyJpk** [Unity-Developer-Community/UDC-Bot#175]
When a user uses `!profile` sometimes it won't appear until the second time they call, the same goes for top/topkarma.

`!profile` I think is just the image/card not being saved to disk before the bot is trying to send it, prob can be fixed by adding a small delay.

Top/TopKarma might be a bit more involved. Needs investigation.

**Comment by Pierre-Demessence** [comment]
It's possible it's on every commands and not just the ones above (it might just feel that way because `!profile` and the `!top` commands are the most used).
