### ISSUE TITLE
Have the bot change profile picture dynamically when writing messages

### ISSUE THREAD

**Issue by Pierre-Demessence** [Unity-Developer-Community/UDC-Bot#21]
The bot could have a different profile picture depending on the message being sent.
Should be doable with https://docs.stillu.cc/api/Discord.SelfUserProperties.html#Discord_SelfUserProperties_Avatar

* The pictures would be local files
* Bot would have a default profile picture for every message where the profile picture is not specified.

I think the easiest way to do this would be create a method that wraps a `SendMessageAsync`, and has a parameter for which picture to use for this message. After sending the message the picture would be reset to the default picture.

⚠️ **To test:** Is the bot rate limited from changing profile picture?

**Comment by SimplyJpk** [comment]
I don't think this would be a good feature. I'm fairly certain the API limits this, but even if it didn't, clients don't pull profile pictures terribly often, so even if you change it, unless it stays there for 5-10 seconds, it probably wouldn't be noticed. 
May also confuse people looking at older messages.
