### ISSUE TITLE
Fix !search and Improve feature

### ISSUE THREAD

**Issue by SimplyJpk** [Unity-Developer-Community/UDC-Bot#24]
Doesn't appear to correctly pull data anymore.

While fixing we should probably use embeds so we can directly link to the page.
Limit description length to reduce spam potential, mayybe reduce max results from 5 to 3.
Alternatively we could try DM the user the results, or only return 1 result to the channel?

**Comment by SimplyJpk** [comment]
Fixed command, and uses embeds now #20 . Could use more improvement. Maybe send DM if user is on mobile?

**Comment by Pierre-Demessence** [comment]
Closed as #20 which fix this has been merged
