### ISSUE TITLE
Fix !top and !topkarma on mobile

### ISSUE THREAD

**Issue by Pierre-Demessence** [Unity-Developer-Community/UDC-Bot#65]
Since it's not possible to show something special for mobile users, may need to completely rethink it.
If task is really impossible, may drop it.

**Comment by Exanite** [comment]
I'm assuming this is what you mean?
![image](https://user-images.githubusercontent.com/42710136/126235879-762f1041-4df4-42d0-8b0e-c193f3ca400c.png)

**Comment by Pierre-Demessence** [comment]
Yes

**Comment by Exanite** [comment]
How does this look as an alternative?

PC:
![image](https://user-images.githubusercontent.com/42710136/126251248-b36d9e03-df67-4eb3-aced-636e47c76b7d.png)

Android (Pixel 4a):
![image](https://user-images.githubusercontent.com/42710136/126251712-12a8f237-3661-47f4-99b9-88eea54b3910.png)

"Unknown user" is used when the user isn't in the discord anymore.
