### ISSUE TITLE
!bday seems to error #VALUE!

### ISSUE THREAD

**Issue by SimplyJpk** [Unity-Developer-Community/UDC-Bot#76]
!bday returns #VALUE!

!bday @user seems to still work.

**Comment by SimplyJpk** [comment]
Seems fixed now, this likely means the input value format was wrong? Simple solution would be to test the value returned from our query.

**Comment by Pierre-Demessence** [comment]
Fixed, it was an issue with the raw data (input values) in the spreadsheet.
